# Generated by Django 4.1.5 on 2023-02-03 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 3, 8, 44, 24, 510738, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
