# Generated by Django 4.1.5 on 2023-02-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_post_date_of_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
