# Generated by Django 4.1.5 on 2023-02-13 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0013_post_vote_ratio_post_vote_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
