# Generated by Django 4.1.5 on 2023-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_post_vote_ratio_remove_post_vote_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='thumbnail/'),
        ),
    ]
