# Generated by Django 4.1.5 on 2023-02-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
